# Generated by Django 4.2.1 on 2023-05-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enq_form_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('ph_num', models.IntegerField()),
                ('course', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
    ]
